config/routes.rb
Rails.application.routes.draw do

  root 'posts#timeline'
  get 'likes/create'
  get 'likes/destroy'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get "users/:id" => "users#show", as: :mypage
  resources :users, only: [:index, :show, :create, :edit, :update, :destroy]
  delete 'posts/:post_id/likes' => 'likes#destroy'
  resources :posts do
    resources :likes, only: [:create]
  end
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]

  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'
  #フォローとフォローを外すアクション

  get 'users/follow_list/:user_id' => 'users#follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list'
  #フォロー・フォロワーの一覧ページ


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :liked_users, through: :likes, source: :user

    mount_uploader :img, ImageUploader

    default_scope -> { order(created_at: :desc) }

    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @like = Like.new
    @search = @posts.ransack(params[:q])
    @posts = @search.result(distinct: true)
 
    @all_ranks = Post.find(Like.group(:post_id).where(created_at: Date.today.in_time_zone.all_day).order('count(post_id) desc').limit(3).pluck(:post_id))

    # like_array = []
    # Like.where(created_at: Date.yesterday.in_time_zone.all_day).each do |like|
    #   like_array.push(like.post_id)
    #   puts (like.post_id)
    # end
    # @like_array = like_array.group_by(&:itself).map{ |key, value| [key, value.count] }.to_h


    respond_to do |format| 
      format.html {render template: "posts/index"}
      format.json { render json: @new_post = Post.where('id > ?', params[:post][:id]) } # json形式でアクセスがあった場合は、params[:message][:id]よりも大きいidがないかMessageから検索して、@new_messageに代入する
   end
  end

  def timeline
    @test = 'test'
    @posts = Post.all
    @like = Like.new
    @search = @posts.ransack(params[:q])
    @posts = @search.result(distinct: true)
    #フォローしている人のidの一覧を取得

    @post_data = Post.where(user_id: current_user.id).group("date(created_at)").count

    array = current_user.follows.map{|follow| follow.followable_id}
    array.push(current_user.id)

    @posts = @posts.where(user_id: array)

   
    respond_to do |format| 
      format.html {render template: "posts/index"}
      format.json { render json: @new_post = Post.where(user_id: array).where('id > ?', params[:post][:id]) } # json形式でアクセスがあった場合は、params[:message][:id]よりも大きいidがないかMessageから検索して、@new_messageに代入する

    end

      
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @like = Like.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    puts "aaa"
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:date, :price, :profit, :news, :factor, :img, :title, :low, :high, :open, :close)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_card.html.erb
<%= link_to "/posts/#{post.id}", class: "post_card_link" do %> 
    <div class="post_card">
        <div class="post_img">
            <% if post.img? %>
                <%= image_tag post.img.url %>
            <% else %>
                <%= image_tag"no-image.png", id: "assets" %>
            <% end %>
        </div>
        <div class="post_user">
            <object>
                <a href="<%= "/users/#{post.user.id}" %>" class="user_img">
                    <% if post.user.image? %>
                        <%= image_tag post.user.image.url %>
                    <% else %>
                        <%= image_tag"no-image.png", id: "assets" %>
                    <% end %>
                </a>
            </object>
            <object>
                <a href="<%= "/users/#{post.user.id}" %>" class="post_name">
                    <%= post.user.name %>
                </a>
            </object>
        </div>
        <div class="post_text">
            <div class="card_title">
                <%= post.title %>
            </div>
            <div class="card_bottom">
                <div class="everyone_common">
                    <div class="good">
                        <% if current_user.already_liked?(post) %>
                            <object>
                                <%= button_to "/posts/#{post.id}/likes", method: :delete, remote: true do %>
                                    <i class="fas fa-heart good_icon"></i>
                                <% end %>
                            </object>
                        <% else %>
                            <object>
                                <%= button_to post_likes_path(post), method: :post, remote: true do %>
                                    <i class="far fa-heart good_icon"></i>
                                <% end %>
                            </object>
                        <% end %>
                        <%= post.liked_users.count %>
                    </div>
                    <div class="card_date">
                        <%= post.date %>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "エラー") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form_field">
    <div class="post_form_wrapper">
      <div class="post_form_day">
        <p class="post_form_sub">日付</p>
        <%= form.date_select :date, date_separator: '/' %>
      </div>
      <div class="post_form_title">
        <p class="post_form_sub">タイトル</p>
        <%= form.text_field :title %>
      </div>
      <div class="post_form_img">
        <p class="post_form_sub">画像を投稿</p>
        <%= form.file_field :img, id: :myImage  %>
      </div>
      <div class="post_img_view">
        <img id="preview">
      </div>
      <div class="post_form_range">
        <div class="post_form_range_list">
          <p class="post_form_sub">始値</p>
          <%= form.number_field :open %>円
        </div>
        <div class="post_form_range_list">
          <p class="post_form_sub">終値</p>
          <%= form.number_field :close %>円
        </div>
      </div>
      <div class="post_form_range">
        <div class="post_form_range_list">
          <p class="post_form_sub red">高値</p>
          <%= form.number_field :high %>円
        </div>
        <div class="post_form_range_list">
          <p class="post_form_sub blue">安値</p>
          <%= form.number_field :low %>円
        </div>
      </div>
      <div class="post_form_price">
        <p class="post_form_sub">収益</p>
        <%= form.number_field :price, value:0 %>円
      </div>
      <div class="post_form_area">
        <p class="post_form_sub">テクニカル分析</p>
        <%= form.text_area :profit %>
      </div>
      <div class="post_form_area">
        <p class="post_form_sub">NEWS</p>
        <%= form.text_area :news %>
      </div>
      <div class="post_form_area">
        <p class="post_form_sub">勝敗に関する要因</p>
        <%= form.text_area :factor %>
      </div>
    </div>
    

    <div class="actions">
      <%= form.submit "送信する" %>
    </div>
  </div>
<% end %>
<script>
  $('#myImage').on('change', function (e) {
    var reader = new FileReader();
    reader.onload = function (e) {
        $("#preview").attr('src', e.target.result);
    }
    reader.readAsDataURL(e.target.files[0]);
  });
</script>

app/views/posts/edit.html.erb
<div id="new_post">
    <div class="new_post">
        <div class="post_back">
            <%= link_to '戻る', posts_path %>
        </div>
        <div class="large_width">
            <h1>編集する</h1>
            <%= render 'form', post: @post %>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<div id="post">
  <div class="large_width">
    <div class="main_post">
      <h2>トレンド</h2>
      <div class="post_rank">
        <% @all_ranks.each do |post| %>
          <%= render 'card', post: post %>
        <% end %>
      </div>
      <h2 class="post_list">投稿一覧</h2>
      <table>
        <tbody>
          <% @posts.each do |post| %>
          <%= render 'card', post: post %>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="side_bar">
      <thead>
        <div class="search_form">
          <%= search_form_for @search do |f| %>
            <div class="search_field">
              <%= f.search_field :title_cont, placeholder: 'キーワード検索' %>
              <%= f.submit "検索" %>
            </div>
          <% end %>

          <%= search_form_for @search ,url: "/users" do |f| %>
            <div class="search_field">
              <%= f.search_field :name_cont, placeholder: 'ユーザー検索' %>
              <%= f.submit "検索" %>
            </div>
          <% end %>

          <%= line_chart Post.where(user_id: current_user.id).group(:date).limit(5).sum(:price) %>
        </div>
      </thead>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div id="new_post">
    <div class="new_post">
        <div class="post_back">
            <%= link_to '戻る', posts_path %>
        </div>
        <div class="large_width">
            <h1>投稿する</h1>

            <%= render 'form', post: @post %>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<div id="post_show">
  <div class="large_width">
    <div class="post_show_img">
      <div class="post_back">
        <div class="show_card_bottom">
          <%= @post.created_at.to_s(:datetime_base) %>
          <div class="good_field">
            <% if current_user.already_liked?(@post) %>
              <%= button_to "/posts/#{@post.id}/likes", method: :delete do %>
                <i class="fas fa-heart good_icon"></i>
              <% end %>
            <% else %>
              <%= button_to post_likes_path(@post) do %>
                <i class="far fa-heart good_icon"></i>
              <% end %>
            <% end %>
            <div class="good_count">
              <%= @post.likes.count %>
            </div>
          </div>
          <div class="post_show_current_user">
            <% if current_user.id == @post.user.id %>
              <%= link_to '編集する', edit_post_path(@post) %> 
              <%= link_to @post, method: :delete, data: { confirm: '削除してよろしいですか？' } do %>
                  <i class="far fa-trash-alt"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="post_show_state">
      <div class="post_show">
        <div class="post_show_card">
          <div class="post_show_top">
            <div class="user_img">
              <%= link_to "/users/#{@post.user.id}" do %>
                <% if @post.user.image? %>
                    <%= image_tag @post.user.image.url %>
                <% else %>
                    <%= image_tag"no-image.png", id: "assets" %>
                <% end %>
              <% end %>
            </div>
            <div class="post_user_name">
              <%= link_to "/users/#{@post.user.id}" do %>
                <%= @post.user.name %>
              <% end %>
            </div>
          </div>
          <p class="post_form_date">
            <%= @post.date %>
          </p>
          <h2 class="post_title">
            <%= @post.title %>
          </h2>
            <div class="post_show_img">
              <% if @post.img? %>
                  <%= image_tag @post.img.url %>
              <% else %>
                  <%= image_tag"no-image.png", id: "assets" %>
              <% end %>
            </div>
          <div class="post_form_list">
            <p class="post_form_sub">収益</p>
            <p class="post_form_data">
              <%= @post.price %>円
            </p>
          </div>
          <div class="post_form_list">
            <p class="post_form_sub">テクニカル分析</p>
            <p class="post_form_data_area">
              <%= @post.profit %>
            </p>
          </div>
          <div class="post_form_list">
            <p class="post_form_sub">NEWS</p>
            <p class="post_form_data_area">
              <%= @post.news %>
            </p>
          </div>
          <div class="post_form_list">
            <p class="post_form_sub">取引内容</p>
            <p class="post_form_data_area">
              <%= @post.factor %>
            </p>
          </div>
        </div>
        </div>
        <div class="side_bar">
          <thead>
            <div class="search_form">
              <%= search_form_for @search do |f| %>
                <div class="search_field">
                  <%= f.search_field :title_cont, placeholder: 'キーワード検索' %>
                  <%= f.submit "検索" %>
                </div>
              <% end %>

              <%= search_form_for @search ,url: "/users" do |f| %>
                <div class="search_field">
                  <%= f.search_field :name_cont, placeholder: 'ユーザー検索' %>
                  <%= f.submit "検索" %>
                </div>
              <% end %>
              <%= line_chart Post.where(user_id: current_user.id).group(:date).limit(5).sum(:price) %>
              <div class="chart_show">
                <div id="img_fix">
                  <% if @post.img? %>
                      <%= image_tag @post.img.url %>
                  <% else %>
                      <%= image_tag"no-image.png", id: "assets" %>
                  <% end %>
                </div>
                <div class="chart_show_price">
                  <div class="price_list">
                    <div class="price_state">
                      <p class="post_form_sub">始値</p>
                      <p class="post_form_data">
                        <%= @post.open %>円
                      </p>
                    </div>
                    <div class="price_state">
                      <p class="post_form_sub">終値</p>
                      <p class="post_form_data">
                        <%= @post.close %>円
                      </p>
                    </div>
                  </div>
                  <div class="price_list">
                    <div class="price_state">
                      <p class="post_form_sub red">高値</p>
                      <p class="post_form_data">
                        <%= @post.high %>円
                      </p>
                    </div>
                    <div class="price_state">
                      <p class="post_form_sub blue">安値</p>
                      <p class="post_form_data">
                        <%= @post.low %>円
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </thead>
        </div>
        <!-- <div class="good_user">
          <% @post.liked_users.each do |user| %>
            <h2 class="good_user_title">いいねしたユーザー</h2>
            <%= link_to "/users/#{user.id}", class: "good_user_link" do %>
              <div class="good_user_list">
                <div class="user_img">
                  <% if @post.user.image? %>
                    <%= image_tag @post.user.image.url %>
                  <% else %>
                    <%= image_tag"no-image.png", id: "assets" %>
                  <% end %>
                </div>
                <div class="good_user_name">
                  <%= user.name %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div> -->
      </div>
    </div>
  </div>
</div>

<script>
  $(function(){
    var fix = $("#img_fix");             //メニューオブジェクトを格納
    var fixTop = fix.offset().top;             //メニューの縦座標を格納
    $(window).scroll(function () {             //スクロールが発生したら開始
      if($(window).scrollTop() >= fixTop) {    //スクロール時の縦座標がメニューの縦座標以上なら…
        fix.css("position","fixed");           //メニューに position:fixed 付与
        fix.css("top","0");                    //メニューに top:0 付与
      } else {
        fix.css("position","");                //メニューの position を空に
        fix.css("top","");                     //メニューの top を空に
      }
    });
  });
</script>